#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""离线生成 PhyWear 动效查表（flash 常量表），并打印精度评估。

为什么要有它（P1-2 动效算法，2026-09-16）：
  UI 动效需要"物理感"，但真机上每帧调用 expf()/sinf() 是纯浪费——同一组曲线
  在一秒钟里被算几百次，而曲线形状是**固定**的。所以：离线算好、存 flash、
  运行时只做"索引 + 线性插值"（整数运算）。本脚本是那份表的唯一来源，
  生成的 pw_motion_table.c 不要手改。

曲线（都用归一化时间 u = t/duration ∈ [0,1]）：

  1) spring：欠阻尼二阶阶跃响应（临界阻尼的推广，带过冲 = "物理手感"）
        ζ = 0.40, ω = 12（每单位 u）
        s(u) = 1 - e^(-ζωu)·[cos(ω_d u) + (ζω/ω_d)·sin(ω_d u)],  ω_d = ω√(1-ζ²)
     过冲峰值 ≈ e^(-ζπ/√(1-ζ²)) ≈ 25%，u=1 时已收敛到 1% 以内。

  2) decay：衰减振荡 e^(-a·u)·sin(2πf·u), a = 6, f = 2（两个周期）
     按实际峰值归一化到 ±1，用于"抖动/脉冲"类反馈。

存储格式：Q14 定点（1.0 = 16384），int16_t。
  选 Q14 而不是 Q16 的原因：spring 有过冲（峰值 1.25），Q16 只能表示到 0.9999；
  Q16+uint32 会把表从 130 B 涨到 260 B，且插值要走 64 位。Q14 的量化步长
  1/16384 = 6.1e-5，远小于插值误差，够用。

用法：
    python3 tools/phywear/gen_motion_table.py            # 打印精度报告 + 写表
    python3 tools/phywear/gen_motion_table.py --check    # 只校验已生成文件是否过期
"""

import argparse
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APP = os.path.join(ROOT, "apps", "examples", "phywear")
OUT = os.path.join(APP, "pw_motion_table.c")

# 表长：N+1 个采样点（含两端），u = i/N。
# 为什么取 128 而不是 64：线性插值误差 ∝ h²，表长翻倍误差降到 1/4，
# 而 flash 只多 260 B、运行时成本完全不变（都是 1 次乘 + 1 次插值）。
N = 128

Q = 14                     # Q14 定点
ONE = 1 << Q               # 1.0

SPRING_ZETA = 0.40
SPRING_OMEGA = 12.0
DECAY_A = 6.0
DECAY_F = 2.0


def spring_raw(u: float) -> float:
    """欠阻尼二阶阶跃响应（未归一）。"""
    z, w = SPRING_ZETA, SPRING_OMEGA
    wd = w * math.sqrt(1.0 - z * z)
    return 1.0 - math.exp(-z * w * u) * (
        math.cos(wd * u) + (z * w / wd) * math.sin(wd * u))


# 关键：把曲线整体除以 s(1)，让**末帧严格落在 1.0**。
# 实测 s_raw(1)=1.0035703（过冲尾巴还没完全衰减），不归一化的话末帧会停在
# 1.0036 —— LVGL path 结束那一拍就从 1.0036 跳回 end_value（位移 200 px 时约 0.7 px）。
# 整体缩放 −0.36% 不影响手感，却消掉这一跳。归一化系数由本脚本生成进表文件，
# 解析式实现引用同一常量，杜绝"脚本改了曲线、C 侧常数没跟着改"的漂移。
_SPRING_K = 1.0 / spring_raw(1.0)


def spring(u: float) -> float:
    return spring_raw(u) * _SPRING_K


def decay_raw(u: float) -> float:
    return math.exp(-DECAY_A * u) * math.sin(2.0 * math.pi * DECAY_F * u)


def build_table(fn, normalize=False):
    """返回 (Q14 整数表, 归一化系数)。"""
    us = [i / N for i in range(N + 1)]
    vals = [fn(u) for u in us]
    k = 1.0
    if normalize:
        peak = max(abs(v) for v in vals)
        k = 1.0 / peak if peak > 0 else 1.0
        vals = [v * k for v in vals]
    tab = [max(-32768, min(32767, int(round(v * ONE)))) for v in vals]
    return tab, k


_DECAY_K = 1.0 / max(abs(decay_raw(i / 100000)) for i in range(100001))


def lerp_table(tab, u: float) -> float:
    """模拟 C 侧实现：索引 + 线性插值（整数路径），返回浮点便于比精度。"""
    x = max(0.0, min(1.0, u)) * N
    i = int(x)
    if i >= N:
        return tab[N] / ONE
    fr = x - i
    # C 侧用整数：((a*(256-f8) + b*f8) >> 8)，这里用等价的浮点表达
    return (tab[i] * (1.0 - fr) + tab[i + 1] * fr) / ONE


def report(name: str, fn, tab, k=1.0):
    """精度：把插值表与解析式在 20 倍密度上逐点比，报最大绝对误差。"""
    worst = 0.0
    worst_u = 0.0
    for j in range(0, N * 20 + 1):
        u = j / (N * 20)
        ref = fn(u) * k
        got = lerp_table(tab, u)
        e = abs(ref - got)
        if e > worst:
            worst, worst_u = e, u
    qerr = 0.5 / ONE
    print("  %-8s 表长 %d×2B=%d B  插值最大误差 %.2e (u=%.3f)  量化上界 %.1e"
          % (name, N + 1, (N + 1) * 2, worst, worst_u, qerr))
    return worst


def emit(tab_spring, tab_decay, path):
    body = []
    body.append("/* %s\n"
                " *\n"
                " * Generated by tools/phywear/gen_motion_table.py -- do not edit by hand.\n"
                " * 曲线参数：spring ζ=%.2f ω=%.1f；decay a=%.1f f=%.1f；表长 %d+1；Q%d 定点。\n"
                " */\n\n"
                % (os.path.basename(path), SPRING_ZETA, SPRING_OMEGA,
                   DECAY_A, DECAY_F, N, Q))
    body.append('#include "pw_motion.h"\n\n')
    body.append("/* 归一化系数：解析式实现（pw_motion.c）引用同一常量，保证与表同一条曲线 */\n")
    body.append("const float pw_motion_spring_k = %.7ff;\n" % _SPRING_K)
    body.append("const float pw_motion_decay_k  = %.7ff;\n\n" % _DECAY_K)
    body.append("/* u = i/%d，Q%d（1.0 = %d）；spring 有过冲，峰值 ≈ 1.25 */\n"
                % (N, Q, ONE))
    body.append("const int16_t pw_motion_tab_spring[PW_MOTION_N] =\n{\n")
    for i in range(0, N + 1, 8):
        body.append("  " + ", ".join("%6d" % v for v in tab_spring[i:i + 8]) + ",\n")
    body.append("};\n\n")
    body.append("/* 衰减振荡 e^(-%.0fu)·sin(2π·%.0fu)，按峰值归一化到 ±1（Q%d） */\n"
                % (DECAY_A, DECAY_F, Q))
    body.append("const int16_t pw_motion_tab_decay[PW_MOTION_N] =\n{\n")
    for i in range(0, N + 1, 8):
        body.append("  " + ", ".join("%6d" % v for v in tab_decay[i:i + 8]) + ",\n")
    body.append("};\n")
    return "".join(body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="只校验文件是否与曲线一致")
    args = ap.parse_args()

    tab_s, _ = build_table(spring)
    tab_d, _ = build_table(decay_raw, normalize=True)

    print("曲线精度评估（N=%d，Q%d，线性插值）：" % (N, Q))
    e1 = report("spring", spring, tab_s)
    e2 = report("decay", decay_raw, tab_d, k=1.0 / max(
        abs(decay_raw(i / N)) for i in range(N + 1)))
    print("  → 误差峰值出现在曲率最大处（u≈0 起步段与过冲拐点），属线性插值的固有形态；")
    print("    对 UI 动画的意义：LVGL path 的 0..1024 分辨率下，%.1e 的归一化误差 = %.2f/1024 个步进"
          % (max(e1, e2), max(e1, e2) * 1024))

    src = emit(tab_s, tab_d, OUT)
    if args.check:
        if not os.path.exists(OUT):
            print("❌ 缺少 %s（先不带 --check 跑一次）" % OUT)
            return 1
        old = open(OUT, encoding="utf-8").read()
        if old != src:
            print("❌ %s 与当前曲线不一致（重新生成）" % OUT)
            return 1
        print("✅ %s 与曲线一致" % OUT)
        return 0

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(src)
    print("已生成 %s（%d B 源码，编译后表占 flash %d B）"
          % (OUT, len(src), (N + 1) * 2 * 2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
